#!/bin/sh
. /etc/rc.d/init.d/functions

GUNICORN=/usr/bin/gunicorn
ROOT=/root/pmapi
PID=/var/run/gunicorn.pid
CONF=$ROOT/gunicorn.py
cd $ROOT
APP="app:app"


case "$1" in
  start)
        echo "Starting deferred execution scheduler" "$APP"
        $GUNICORN -c  $CONF --pid=$PID $APP 2>&1 >/dev/null &
        echo  $?
    ;;
  stop)
        echo "Stopping deferred execution scheduler" "$APP"
        killproc -p $PID $GUNICORN
        echo $?
    ;;
  force-reload|restart)
    $0 stop
    $0 start
    ;;
  status)
    status -p $PID $GUNICORN && exit 0 || exit $?
    ;;
  reload)
    kill -HUP   `cat $PID` && exit 0 || exit $?
    ;;
  *)
    echo "Usage: /etc/init.d/gunicorn {start|stop|restart|force-reload|status}"
    exit 1
    ;;
esac

exit 0
